#!/bin/sh

ip=
nfsroot=
root=

set -- $(cat /proc/cmdline)
for arg do
	key=${arg%%=*}
	if [ "$arg" = "$key" ]; then
		val=
	else
		val=${arg#*=}
	fi
	case "$key" in
		ip)
			ip=${val%%:*}
			;;
		nfsroot)
			nfsroot=$val
			;;
		root)
			root=$val
			;;
	esac
done

options=

if [ "$root" = "/dev/nfs" -o -n "$nfsroot" -a -n "$ip" ]; then
	set -- $(ip -4 -o addr show | awk '{print $2}')
	for dev do
		if ip -o link show $dev | awk '{print $3}' | grep -qvw -e 'LOOPBACK' -e 'NO-CARRIER'; then
			case "$ip" in
				any|bootp|both|dhcp|on|rarp)
					options="-I $dev $options"
					;;
				*)
					for dev_addr in $(ip -4 -o addr show dev $dev | awk '{print $4}' | grep -o '^[0-9.]\+'); do
						if [ "$ip" = "$dev_addr" ]; then
							options="-I $dev"
							break
						fi
					done
					;;
			esac
		fi
	done
fi

[ -d /run/connmand ] || mkdir -p /run/connmand
echo "CONNMAND_OPTS=$options" >/run/connmand/connmand.env
