inherit image

BAD_RECOMMENDATIONS += "busybox-syslog"

IMAGE_FEATURES = ""
IMAGE_FSTYPES = "${INITRAMFS_FSTYPES}"
IMAGE_INSTALL = "busybox dropbear"
IMAGE_LINGUAS = ""
IMAGE_ROOTFS_SIZE = "8192"

USE_DEVFS = "1"
